"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-04-29 20:33:34.167683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_cache',
    sa.Column('filter_id', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_s3_key', sa.String(length=1024), nullable=True),
    sa.Column('issue_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('filter_id', name=op.f('pk_jira_cache'))
    )
    op.create_table('s3_image_cache',
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('s3_url', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('first_uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('content_sha256', name=op.f('pk_s3_image_cache'))
    )
    op.create_table('skilljar_courses',
    sa.Column('skilljar_course_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('version_label', sa.String(length=32), nullable=True),
    sa.Column('raw_meta_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('skilljar_course_id', name=op.f('pk_skilljar_courses'))
    )
    op.create_index(op.f('ix_skilljar_courses_slug'), 'skilljar_courses', ['slug'], unique=False)
    op.create_index(op.f('ix_skilljar_courses_version_label'), 'skilljar_courses', ['version_label'], unique=False)
    op.create_table('skilljar_published_paths',
    sa.Column('skilljar_path_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('course_ids_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('skilljar_path_id', name=op.f('pk_skilljar_published_paths'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('picture_url', sa.String(length=1024), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('session_epoch', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('to_version', sa.String(length=32), nullable=True),
    sa.Column('scope_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], name=op.f('fk_jobs_owner_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_owner'), 'jobs', ['owner'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('to_version', sa.String(length=32), nullable=True),
    sa.Column('scope_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('options_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fargate_task_arn', sa.String(length=512), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('parent_run_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_runs_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['runs.id'], name=op.f('fk_runs_parent_run_id_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs'))
    )
    op.create_index(op.f('ix_runs_created_at'), 'runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_runs_created_by'), 'runs', ['created_by'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_index(op.f('ix_runs_to_version'), 'runs', ['to_version'], unique=False)
    op.create_table('skilljar_lessons',
    sa.Column('skilljar_lesson_id', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('content_s3_key', sa.String(length=1024), nullable=True),
    sa.Column('content_html_hash', sa.String(length=128), nullable=True),
    sa.Column('last_modified_remote', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['skilljar_courses.skilljar_course_id'], name=op.f('fk_skilljar_lessons_course_id_skilljar_courses'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('skilljar_lesson_id', name=op.f('pk_skilljar_lessons'))
    )
    op.create_index('ix_skilljar_lessons_course_id', 'skilljar_lessons', ['course_id'], unique=False)
    op.create_table('content_cache',
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('s3_key', sa.String(length=1024), nullable=True),
    sa.Column('payload_summary_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_hit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_by_run_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['created_by_run_id'], ['runs.id'], name=op.f('fk_content_cache_created_by_run_id_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('fingerprint', name=op.f('pk_content_cache'))
    )
    op.create_index(op.f('ix_content_cache_kind'), 'content_cache', ['kind'], unique=False)
    op.create_table('lesson_drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('to_version', sa.String(length=32), nullable=False),
    sa.Column('source_skilljar_lesson_id', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_lesson_drafts_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_lesson_drafts_run_id_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_skilljar_lesson_id'], ['skilljar_lessons.skilljar_lesson_id'], name=op.f('fk_lesson_drafts_source_skilljar_lesson_id_skilljar_lessons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_lesson_drafts_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_drafts'))
    )
    op.create_index(op.f('ix_lesson_drafts_status'), 'lesson_drafts', ['status'], unique=False)
    op.create_index(op.f('ix_lesson_drafts_to_version'), 'lesson_drafts', ['to_version'], unique=False)
    op.create_index('ix_lesson_drafts_to_version_path', 'lesson_drafts', ['to_version', 'path'], unique=False)
    op.create_table('release_locks',
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('locked_by', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('intent', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], name=op.f('fk_release_locks_locked_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_release_locks_run_id_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('target_id', name=op.f('pk_release_locks'))
    )
    op.create_table('run_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_logs_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_logs'))
    )
    op.create_index('ix_run_logs_run_id_id', 'run_logs', ['run_id', 'id'], unique=False)
    op.create_table('run_steps',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('step_num', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_usage_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('artifact_keys_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_steps_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'step_num', name='pk_run_steps')
    )
    op.create_table('release_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('skilljar_lesson_id', sa.String(length=64), nullable=True),
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('before_hash', sa.String(length=128), nullable=True),
    sa.Column('after_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('conflict_warning_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['lesson_drafts.id'], name=op.f('fk_release_history_draft_id_lesson_drafts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_release_history_run_id_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skilljar_lesson_id'], ['skilljar_lessons.skilljar_lesson_id'], name=op.f('fk_release_history_skilljar_lesson_id_skilljar_lessons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_release_history_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_release_history'))
    )
    op.create_index('ix_release_history_skilljar_lesson_id', 'release_history', ['skilljar_lesson_id'], unique=False)
    op.create_index('ix_release_history_target_id', 'release_history', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_release_history_target_id', table_name='release_history')
    op.drop_index('ix_release_history_skilljar_lesson_id', table_name='release_history')
    op.drop_table('release_history')
    op.drop_table('run_steps')
    op.drop_index('ix_run_logs_run_id_id', table_name='run_logs')
    op.drop_table('run_logs')
    op.drop_table('release_locks')
    op.drop_index('ix_lesson_drafts_to_version_path', table_name='lesson_drafts')
    op.drop_index(op.f('ix_lesson_drafts_to_version'), table_name='lesson_drafts')
    op.drop_index(op.f('ix_lesson_drafts_status'), table_name='lesson_drafts')
    op.drop_table('lesson_drafts')
    op.drop_index(op.f('ix_content_cache_kind'), table_name='content_cache')
    op.drop_table('content_cache')
    op.drop_index('ix_skilljar_lessons_course_id', table_name='skilljar_lessons')
    op.drop_table('skilljar_lessons')
    op.drop_index(op.f('ix_runs_to_version'), table_name='runs')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_created_by'), table_name='runs')
    op.drop_index(op.f('ix_runs_created_at'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_jobs_owner'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('skilljar_published_paths')
    op.drop_index(op.f('ix_skilljar_courses_version_label'), table_name='skilljar_courses')
    op.drop_index(op.f('ix_skilljar_courses_slug'), table_name='skilljar_courses')
    op.drop_table('skilljar_courses')
    op.drop_table('s3_image_cache')
    op.drop_table('jira_cache')
    # ### end Alembic commands ###
