"""runs.report_regenerated_at

Revision ID: 0004
Revises: 0003
Create Date: 2026-06-12 14:30:00.000000

KNOW-2348 (regen UX rework) — record when a run's HTML report was last
(re)generated by the manual "Regen Report" action, so Recent Runs can show
an "Updated" timestamp distinct from ``created_at``. Nullable: existing rows
(and runs that have never been regenerated) simply have no value.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: Union[str, Sequence[str], None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "runs",
        sa.Column(
            "report_regenerated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )


def downgrade() -> None:
    op.drop_column("runs", "report_regenerated_at")
