"""Convenience redirect for the per-run HTML report (KNOW-2334).

``GET /report/{run_id}`` redirects to the static artifact served by the
``/artifacts`` mount, so users can share a stable URL like
``https://fme-train.base.safe.com/report/20260610T120000-abcd``
without knowing the full artifact path.

The report HTML is generated by ``pipeline/report.py:build_report`` and
written to ``<artifacts_root>/<run_id>/report-<run_id>.html``.  The
``/artifacts`` static mount (configured in ``app/main.py``) serves that
directory tree, so the canonical URL is
``/artifacts/<run_id>/report-<run_id>.html``.

This module is intentionally minimal — no DB lookup, no auth gate, just a
redirect.  Auth is enforced at the middleware level for /api/* paths; the
/artifacts static files are public within the network (office-IP firewall
is the perimeter).
"""
from __future__ import annotations

from fastapi import APIRouter, Request
from fastapi.responses import RedirectResponse

router = APIRouter(tags=["report"])


@router.get("/report/{run_id}", response_class=RedirectResponse)
async def redirect_to_report(run_id: str, request: Request) -> RedirectResponse:
    """Redirect ``/report/{run_id}`` to the static HTML report artifact.

    Returns 302 so browsers and curl follow the redirect automatically.
    The target URL is same-origin (``/artifacts/...``) so the report's
    embedded ``fetch()`` calls to ``/api/runs/{run_id}/report-drafts``
    work without CORS plumbing. Any query string is forwarded (e.g.
    ``/report/{run_id}?tab=lesson-edits``) so callers can deep-link to a
    report tab without hand-building the per-run artifact path (KNOW-2355).
    """
    target = f"/artifacts/{run_id}/report-{run_id}.html"
    if request.url.query:
        target += f"?{request.url.query}"
    return RedirectResponse(url=target, status_code=302)
