name: Sync Entire S3 Bucket to Repo
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:    # Allows you to click "Run workflow" manually in GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Sync from S3 (Public/Anonymous)
        run: |
          # Syncs safeskilljar to root, but ignores your GitHub-specific files
          aws s3 sync s3://safeskilljar/ ./ --delete --no-sign-request \
          --exclude ".git/*" \
          --exclude ".github/*" \
          --exclude ".gitignore" \
          --exclude "README.md" \
          --exclude "2021*/*" \
          --exclude "2022*/*" \
          --exclude "2023*/*" \
          --exclude "2024*/*" \
          --exclude "lababuse.html" \
          --exclude "LICENSE.md"
          
      - name: Commit and Push
        run: |
          git config --global user.name "rjcragg"
          git config --global user.email "ryan.cragg@safe.com"
          
          # Force add everything including hidden files
          git add -A
          
          # Check status in logs so we can see what Git found
          git status
          
          # Commit only if there are changes
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Automated sync from safeskilljar S3"
            git push
          else
            echo "No changes detected between S3 and GitHub."
          fi